version: "3"

services:
  archlinux:
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/1000/gdm/Xauthority:/home/[USERNAME]/.Xauthority
    hostname: ${HOSTNAME}
    network_mode: host
    restart: always
    container_name: 'archlinux'
    privileged: true
