version: "3"

services:
  archlinux:
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/[HOST_USER_ID]/gdm/Xauthority:/home/[USERNAME]/.Xauthority
    network_mode: host
    restart: always
    container_name: 'arch_gui'
    privileged: true
